name: PowerShell Script Trigger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run PowerShell script
      shell: powershell
      run: |
        ./Pipeline/PowerShellScripts/UpdateVersion.ps1
