name: Update Version Number

on:  
  push:    
    branches: 
    - main
  pull_request:
    branches: 
    - main
    
jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          targetType: filePath
          filePath: ./Pipeline/PowerShellScripts/UpdateVersion.ps1
          arguments: '-RelativePath "$(Build.SourcesDirectory)\src\POS.NorhtAmerica\"'
          failOnStderr: true
    
